version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peru4321$
      POSTGRES_DB: postgres  # Cambié el nombre de la base de datos a 'postgres' como predeterminado
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistencia de datos

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    command: npm run dev

volumes:
  db_data:
