name: Deploy AnuncIA to AWS

on:
  push:
    branches:
      - main  # Ejecutar el despliegue cada vez que haya un push a la rama main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install backend dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Zip backend code
      run: zip -r backend.zip backend/ main.py requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Cambia a tu región de AWS

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name anunc-ia-backend \
          --zip-file fileb://backend.zip

  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Versión de Node.js que usas para tu frontend

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        npm run build

    - name: Sync with S3
      run: |
        aws s3 sync frontend/build/ s3://anunc-ia-frontend --delete
