# .github/workflows/deploy.yml
name: Deploy AnuncIA to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Set environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Create Lambda Layer
      run: |
        mkdir -p lambda_layer/python
        pip install --upgrade pip
        pip install --no-cache-dir -r backend/requirements.txt -t lambda_layer/python
        pip install --no-cache-dir ddtrace -t lambda_layer/python
        find lambda_layer/python -name "*.pyc" -delete
        find lambda_layer/python -name "__pycache__" -delete
        find lambda_layer/python -name "*.md" -delete
        find lambda_layer/python -name "tests" -type d -exec rm -rf {} +
        zip -r lambda_layer.zip lambda_layer
        LAYER_SIZE=$(du -b lambda_layer.zip | cut -f1)
        echo "Layer size: $LAYER_SIZE bytes"
        if [ $LAYER_SIZE -gt 52428800 ]; then
          echo "Layer size exceeds 50 MB limit."
          exit 1
        fi

    - name: Deploy Lambda Layer
      id: deploy_layer
      run: |
        LAYER_NAME="anunc-ia-dependencies"
        LAYER_VERSION=$(aws lambda list-layer-versions --layer-name $LAYER_NAME --query 'LayerVersions[-1].Version' --output text 2>/dev/null || echo "0")
        if [[ "$LAYER_VERSION" == "0" ]]; then
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name $LAYER_NAME \
            --description "Dependencies for AnuncIA backend" \
            --zip-file fileb://lambda_layer.zip \
            --compatible-runtimes python3.12 \
            --query 'LayerVersionArn' \
            --output text)
        else
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name $LAYER_NAME \
            --description "Dependencies for AnuncIA backend v$(($LAYER_VERSION + 1))" \
            --zip-file fileb://lambda_layer.zip \
            --compatible-runtimes python3.12 \
            --query 'LayerVersionArn' \
            --output text)
        fi
        echo "::set-output name=layer_arn::$LAYER_ARN"

    - name: Install dependencies globally
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir -r requirements.txt
        python -m pip list

    - name: Verify Alembic Installation
      working-directory: ./backend
      run: |
        python -m alembic --version

    - name: Apply Alembic migrations
      working-directory: ./backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python -m alembic upgrade head

    - name: Run tests with coverage
      env:
        REDIS_URL: redis://localhost:6379
        DATABASE_URL: "sqlite:///:memory:"
      working-directory: ./backend
      run: |
        python -m pip install --no-cache-dir coverage
        coverage run --rcfile=.coveragerc -m pytest tests
        coverage report
        coverage xml -o coverage.xml
      continue-on-error: true

    - name: Prepare Lambda package
      working-directory: ./backend
      run: |
        zip -r ../backend.zip main.py
        ZIP_SIZE=$(du -b ../backend.zip | cut -f1)
        echo "Backend package size: $ZIP_SIZE bytes"
        if [ $ZIP_SIZE -gt 52428800 ]; then
          echo "Backend package size exceeds 50 MB limit."
          exit 1
        fi

    - name: List ZIP contents (Debugging Step)
      run: unzip -l backend.zip

    - name: Deploy to AWS Lambda
      run: |
        LAYER_ARN=${{ steps.deploy_layer.outputs.layer_arn }}
        aws lambda update-function-configuration \
          --function-name anunc-ia-backend \
          --layers $LAYER_ARN
        aws lambda wait function-updated --function-name anunc-ia-backend
        aws lambda update-function-code \
          --function-name anunc-ia-backend \
          --zip-file fileb://backend.zip

  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Skip deployment in development mode
      if: ${{ github.event_name == 'push' }}
      run: echo "Development build, skipping deployment."

    - name: Build frontend (only for production)
      if: ${{ github.event_name != 'push' }}
      run: |
        cd frontend
        npm run build

    - name: Deploy to S3 (only if build exists)
      if: ${{ github.event_name != 'push' }}
      run: |
        if [ -d "frontend/build" ]; then
          aws s3 sync frontend/build/ s3://anunc-ia-frontend --delete
        else
          echo "Build folder not found, skipping S3 sync"
        fi
