name: Deploy AnuncIA to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install dependencies and package code
      working-directory: ./backend
      run: |
        # Limpiar y crear el directorio de build
        rm -rf build
        mkdir -p build

        # Instalar dependencias en la carpeta de build
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt -t build

        # Eliminar archivos innecesarios
        find build -name '*.pyc' -delete
        find build -name '__pycache__' -delete

        # Crear el archivo ZIP
        cd build
        zip -r9 ../backend.zip .
        cd ..

        # Subir el archivo ZIP al bucket de S3
        aws s3 cp backend.zip s3://anunc-ia-lambda-packages/backend.zip

    - name: Update Lambda function
      run: |
        aws lambda update-function-code \
          --function-name anunc-ia-backend \
          --s3-bucket anunc-ia-lambda-packages \
          --s3-key backend.zip

  deploy_frontend_after_backend:
    runs-on: ubuntu-latest
    needs: deploy_backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Verify dist directory exists
      run: |
        if [ ! -d "frontend/dist" ]; then
          echo "Error: Dist directory not found. Exiting."
          exit 1
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy frontend to S3
      run: |
        aws s3 sync frontend/dist/ s3://anunc-ia-frontend --delete
